prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> 
prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#>

select (count(?text) as ?count) ?text WHERE{ 
 ?s itsrdf:taClassRef ?class .
 ?s nif:anchorOf ?text .
 ?s itsrdf:taClassRef <$0$>
}
group by ?text
order by desc (?count)
LIMIT 20