prefix nif: <http://persistence.uni-leipzig.org/nlp2rdf/ontologies/nif-core#> 
prefix itsrdf: <http://www.w3.org/2005/11/its/rdf#>

select ?uri ?anchor WHERE{ 
 ?uri a nif:Context .
 ?s  nif:referenceContext ?uri .
 ?s nif:anchorOf ?anchor 
}
